name: Run Crawler

on:
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build crawler
        run: cargo build --release -p crawler

      - name: Run crawler
        run: cargo run --release -p crawler
