name: Run Crawler

on:
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            .

      - name: Build crawler
        timeout-minutes: 20
        run: cargo build --release -p crawler

      - name: Run crawler
        timeout-minutes: 330
        env:
          MONGO_DB_URL: ${{ vars.MONGO_DB_URL }}
          IS_PROXY: ${{ vars.IS_PROXY }}
          MAX_REQUESTS_WITH_EACH_PROXY: ${{ vars.MAX_REQUESTS_WITH_EACH_PROXY }}
          MAX_CONCURRENCY: ${{ vars.MAX_CONCURRENCY }}

        run: ./target/release/crawler
